/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package FirstWebApp;

import java.util.ArrayList;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }

    public static boolean containsMean(ArrayList<Integer> array,int first,int second,int third){

        if(array==null){
            return false;
        }

        int mean = (first+second+third)/3;

        for(int a:array){
            if(mean==a){
                return true;
            }
        }    

        return false;
    }
}
