/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package FirstWebApp;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.util.ArrayList;
import java.util.Arrays;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    @Test void testFound(){
        ArrayList<Integer> array = new ArrayList<>(Arrays.asList(1,8,4,5,6));
        assertTrue(App.containsMean(array, 5, 6, 4));
    }

    @Test void testNotFound(){
        ArrayList<Integer> array = new ArrayList<>(Arrays.asList(1,4,2,5,9));
        assertFalse(App.containsMean(array, 7, 5, 9));
    }

    @Test void testEmptyArray(){
        ArrayList<Integer> array = new ArrayList<>();
        assertFalse(App.containsMean(array, 7, 6, 8));
    }

    @Test void testNegativeNumber(){
        ArrayList<Integer> array = new ArrayList<>(Arrays.asList(-4,-7,9,-5,6));
        assertTrue(App.containsMean(array, -13, -4, 5));
    }

    @Test void testNullArray(){
        ArrayList<Integer> array = null;
        assertFalse(App.containsMean(array, 5, 6, 4));
    }
}
